import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'rc-slider/assets/index.css';
import { AuthProvider } from '../context/AuthContext'; // 1. Importa el proveedor de Auth
import AuthGuard from '../components/AuthGuard';     // 2. Importa el AuthGuard

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider> {/* 3. Envuelve todo con el AuthProvider */}
          <AuthGuard>  {/* 4. Dentro, envuelve los children con AuthGuard */}
            {children}
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
