name: Actualizar BCRA

on:
  schedule:
    - cron: "30 12 * * *" # 09:30 Argentina = 12:30 UTC
  workflow_dispatch: # para ejecutarlo manualmente también

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install @supabase/supabase-js node-fetch

      - name: Run update
        run: node update.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
